apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  labels:
    app: demo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      imagePullSecrets:
        - name: artifactory-pull-secret
      containers:
        - name: frontend
          image: artifactory.octopussamples.com/demo-enterprise-docker/cbidigital.frontend:CHANGE_ME_TAG
          ports:
            - containerPort: 5151
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5151"
            - name: ApiBaseUrl
              value: "http://demo-api/api"
