apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./api
  - ./frontend

#ÃŸnamespace: development-ns

# Manage scaling here
replicas:
  - name: demo-api
    count: 2
  - name: demo-frontend
    count: 1

# Manage versions here
images:
  - name: ghcr.io/adamoctoclose/financiadigital.api
    newTag: "1.0.0.6"
  - name: ghcr.io/adamoctoclose/financiadigital.frontend
    newTag: "1.0.0.5"