apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This aggregates both apps into one manifest stream
resources:
  - ./api
  - ./frontend

# This ensures everything in this Argo App lands in the right namespace
namespace: financia-development-kust 

# Optional: Add a common label to everything in this environment
commonLabels:
  env: development